from enum import Enum

class ResponseSignal(Enum):

    FILE_VALIDATED_SUCCESS = "FILE_VALIDATED_SUCCESSFULLY"
    FILE_TYPE_UNSUPPORTED = "FILE_TYPE_UNSUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOADED_SUCCESS = "FILE_UPLOADED_SUCCESSFULLY"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    PROCESSING_SUCCESS = "PROCESSING_COMPLETED_SUCCESSFULLY"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    
    